apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: betterstack-heartbeat-url
  namespace: uptime-monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: ${BETTERSTACK_HEARTBEAT_K8S_SECRET_NAME}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        url: "{{ .heartbeat_url }}"
  data:
    - secretKey: heartbeat_url
      remoteRef:
        key: "${BETTERSTACK_HEARTBEAT_URL_SECRET_NAME}"
