apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: oci-nlb-proxy
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDaemonSet:
        container:
          resources:
            requests:
              cpu: 5m
              memory: 256Mi
            limits:
              memory: 512Mi

      envoyService:
        externalTrafficPolicy: Local
        annotations:
          oci.oraclecloud.com/load-balancer-type: "nlb"
          oci-network-load-balancer.oraclecloud.com/external-ip-only: "true"
          oci-network-load-balancer.oraclecloud.com/is-preserve-source: "false"
          oci-network-load-balancer.oraclecloud.com/is-instant-failover-enabled: "true"
          oci-network-load-balancer.oraclecloud.com/health-check-interval: "10000"
          oci-network-load-balancer.oraclecloud.com/health-check-timeout: "1000"
          oci-network-load-balancer.oraclecloud.com/health-check-retries: "1"

